# -*- coding: utf-8 -*-
"""project 1 level 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k92VlQLU8jYVrx-WIMEoxeD9z4OVk0Sn
"""

#Project 1 Proposal level 1

#Idea: Exploratory Data Analysis (EDA) on Retail Sales Data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/retail_sales_dataset.csv')

data.head()

data['Date']=pd.to_datetime(data["Date"],errors='coerce')

data.isnull().sum()

data

data.describe()

duplicates = data.duplicated().sum()
if duplicates > 0:
    data.drop_duplicates(inplace=True)

duplicates

# add new column
data['year'] = data['Date'].dt.year
data['month'] = data['Date'].dt.month_name()
data['day'] = data['Date'].dt.day_name()

data

#Sales Trend Over Time
plt.figure(figsize=(10, 5))
data.groupby('month')['Total Amount'].sum().plot(kind='line',marker='o',color='black')
plt.ylabel('Total Amount')
plt.grid()
plt.xticks(rotation=45)
plt.xlabel('month')
plt.title('Sales Trend Over Time')
plt.show()

#sale by gander
sal_gender=data.groupby('Gender')['Total Amount'].sum()
sal_gender

plt.bar(sal_gender.index, sal_gender.values,color=['blue','green'])
plt.xlabel('Gender')
plt.ylabel('Total Amount')
plt.title('Total Sales by Gender')
plt.show()

top_product =data.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False).head(10)
top_product.plot(kind='bar',color='red')
plt.xlabel('Product Category')
plt.ylabel('Total Amount')
plt.title('Top 10 Product Categories by Sales')

#Age Distribution of customers
sns.histplot(data['Age'],bins=20,kde=True,color='orange')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution of Customers')
plt.show()

sns.heatmap(data.corr(numeric_only=True),annot=True,cmap='coolwarm',linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

#Predicting House Prices with Linear Regression

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Housing.csv')

df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

df.info()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype('category').cat.codes

df.isnull().sum()
df.duplicated().sum()

sns.pairplot(df)
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

df.head()

x=df.drop('price',axis=1)
y=df['price']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

Lr=LinearRegression()

Lr.fit(x_train,y_train)

prediction=Lr.predict(x_test)

Lr.score(x_train,y_train)

Lr.score(x_test,y_test)

mse=mean_squared_error(y_test,Lr.predict(x_test))
mse

mae=mean_absolute_error(y_test,Lr.predict(x_test))
mae

R2=r2_score(y_test,Lr.predict(x_test))
R2

sns.scatterplot(x=y_test, y=prediction,color="black")
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual vs Predicted Prices')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red')

plt.show()

